name: Build Client

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/build-client.yml'
  pull_request:
    paths:
      - 'client/**'
      - '.github/workflows/build-client.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      # - name: Lint
      #   run: npm run lint
